version: '3'
services:
  proxy_pool:
    image: jhao104/proxy_pool
    container_name: proxy_pool
    expose:
      - 5010
    links:
      - proxy_redis
    environment:
      DB_CONN: "redis://@proxy_redis:6379/0"
    
  proxy_redis:
    image: redis:alpine
    container_name: proxy_redis
  
  dmi_account:
    image: ghcr.io/pubpack/dmi-account:main
    container_name: dmi_account
    pull_policy: always
    links:
      - proxy_pool
    environment:
      PROXY_ADDRESS_POP: http://proxy_pool:5010/pop?type=https
      # 允许同时 50 个请求
      MAX_CONNECTION: 50
      # 超时时长
      CONN_TIMEOUT: 8000
    volumes:
      # 绑定生成的账号文件目录到指定目录
      - ./csv/:/app/out/
  